nodeLinker: node-modules
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "31291482-48EF-4170-80D5-73AEDC4EE11F"
  awesome.me:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    npmAuthToken: "31291482-48EF-4170-80D5-73AEDC4EE11F"
